apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stack-auth
  namespace: six-degrees-apps
  annotations:
    cert-manager.io/cluster-issuer: http01-clusterissuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sso.6degrees.com.sa
        - sso.dashboard.6degrees.com.sa
      secretName: stack-auth-tls
  rules:
    - host: sso.6degrees.com.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stack-auth-service
                port:
                  number: 8102
    - host: sso.dashboard.6degrees.com.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stack-auth-service
                port:
                  number: 8101
