apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redisinsight-secret
  namespace: redis
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: redisinsight-secret
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: redis/redisinsight/ui-secret
        property: auth
