apiVersion: v1
kind: ConfigMap
metadata:
  name: stack-auth-configmap
  namespace: six-degrees-apps
data:
  NEXT_PUBLIC_STACK_PROJECT_ID: "internal"
  NEXT_PUBLIC_STACK_API_URL: "https://sso.6degrees.com.sa"
  NEXT_PUBLIC_BROWSER_STACK_API_URL: "https://sso.6degrees.com.sa"
  NEXT_PUBLIC_STACK_DASHBOARD_URL: "https://sso.6degrees.com.sa"
  NEXT_PUBLIC_BROWSER_STACK_DASHBOARD_URL: "https://sso.6degrees.com.sa"
  STACK_SEED_INTERNAL_PROJECT_ALLOW_LOCALHOST: "false"
  STACK_SEED_INTERNAL_PROJECT_SIGN_UP_ENABLED: "false"
  STACK_RUN_MIGRATIONS: "true"
  STACK_RUN_SEED_SCRIPT: "false"
  STACK_CLICKHOUSE_URL: "http://stack-auth-clickhouse:8123"
