apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-auth-secret
  namespace: redis
  labels:
    app: redis
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: redis-auth
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: redis/secret
        property: password 