apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis-tcp
    port: 6379
    protocol: TCP
    targetPort: 6379
  type: ClusterIP
