apiVersion: apps/v1
kind: Deployment
metadata:
  name: unsend-smtp-server
  namespace: six-degrees-apps
spec:
  selector:
    matchLabels:
      app: unsend-smtp-server
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: unsend-smtp-server
    spec:
      containers:
      - name: unsend-smtp-server
        image: unsend/smtp-proxy:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SMTP_AUTH_USERNAME
          valueFrom:
            configMapKeyRef:
              name: unsend-configmap
              key: SMTP_AUTH_USERNAME
        - name: UNSEND_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: unsend-configmap
              key: UNSEND_BASE_URL
        - name: UNSEND_API_KEY_PATH
          value: "/certs/tls.key"
        - name: UNSEND_API_CERT_PATH
          value: "/certs/tls.crt"
        envFrom:
        - secretRef:
            name: unsend-secret
        - configMapRef:
            name: unsend-configmap
        ports:
        - containerPort: 25
          name: smtp
        - containerPort: 587
          name: smtp-submission
        - containerPort: 2587
          name: smtp-alt
        - containerPort: 465
          name: smtps
        - containerPort: 2465
          name: smtps-alt
        volumeMounts:
        - name: smtp-tls-certs
          mountPath: /certs
          readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
      volumes:
      - name: smtp-tls-certs
        secret:
          secretName: smtp-tls-secret
