apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-tcp-services
  namespace: default
  labels:
    app: ingress-nginx
    component: tcp-services
data:
  # SMTP Services (Unsend)
  "25": "six-degrees-apps/unsend-smtp-server:25"
  "587": "six-degrees-apps/unsend-smtp-server:587"
  "2587": "six-degrees-apps/unsend-smtp-server:2587"
  "465": "six-degrees-apps/unsend-smtp-server:465"
  "2465": "six-degrees-apps/unsend-smtp-server:2465"
  # Redis Service
  "6379": "redis/redis:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-udp-services
  namespace: default
  labels:
    app: ingress-nginx
    component: udp-services
data: {} 