controller:
  # Enable TCP services
  config:
    # Reference to the ConfigMap containing TCP service mappings
    tcp-services-configmap: "default/nginx-tcp-services"
    udp-services-configmap: "default/nginx-udp-services"
  
  # Add explicit command line arguments for TCP/UDP services
  extraArgs:
    tcp-services-configmap: "default/nginx-tcp-services"
    udp-services-configmap: "default/nginx-udp-services"
  
  service:
    ports:
      http: 80
      https: 443
      # SMTP Ports
      smtp: 25
      smtp-submission: 587
      smtp-alt: 2587
      smtps: 465
      smtps-alt: 2465
    targetPorts:
      http: http
      https: https
      smtp: 25
      smtp-submission: 587
      smtp-alt: 2587
      smtps: 465
      smtps-alt: 2465
    nodePorts:
      http: ""
      https: ""
      tcp:
        25: ""
        587: ""
        2587: ""
        465: ""
        2465: "" 